/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.parser;

import de.tuberlin.cs.cis.ocl.parser.node.*;
import de.tuberlin.cs.cis.ocl.parser.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTSet(@SuppressWarnings("unused") TSet node)
    {
        this.index = 0;
    }

    @Override
    public void caseTBag(@SuppressWarnings("unused") TBag node)
    {
        this.index = 1;
    }

    @Override
    public void caseTSequence(@SuppressWarnings("unused") TSequence node)
    {
        this.index = 2;
    }

    @Override
    public void caseTCollection(@SuppressWarnings("unused") TCollection node)
    {
        this.index = 3;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 4;
    }

    @Override
    public void caseTArrow(@SuppressWarnings("unused") TArrow node)
    {
        this.index = 5;
    }

    @Override
    public void caseTNot(@SuppressWarnings("unused") TNot node)
    {
        this.index = 6;
    }

    @Override
    public void caseTMult(@SuppressWarnings("unused") TMult node)
    {
        this.index = 7;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 8;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 9;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 10;
    }

    @Override
    public void caseTContext(@SuppressWarnings("unused") TContext node)
    {
        this.index = 11;
    }

    @Override
    public void caseTPre(@SuppressWarnings("unused") TPre node)
    {
        this.index = 12;
    }

    @Override
    public void caseTPost(@SuppressWarnings("unused") TPost node)
    {
        this.index = 13;
    }

    @Override
    public void caseTInv(@SuppressWarnings("unused") TInv node)
    {
        this.index = 14;
    }

    @Override
    public void caseTDef(@SuppressWarnings("unused") TDef node)
    {
        this.index = 15;
    }

    @Override
    public void caseTEqual(@SuppressWarnings("unused") TEqual node)
    {
        this.index = 16;
    }

    @Override
    public void caseTNEqual(@SuppressWarnings("unused") TNEqual node)
    {
        this.index = 17;
    }

    @Override
    public void caseTLt(@SuppressWarnings("unused") TLt node)
    {
        this.index = 18;
    }

    @Override
    public void caseTGt(@SuppressWarnings("unused") TGt node)
    {
        this.index = 19;
    }

    @Override
    public void caseTLteq(@SuppressWarnings("unused") TLteq node)
    {
        this.index = 20;
    }

    @Override
    public void caseTGteq(@SuppressWarnings("unused") TGteq node)
    {
        this.index = 21;
    }

    @Override
    public void caseTAnd(@SuppressWarnings("unused") TAnd node)
    {
        this.index = 22;
    }

    @Override
    public void caseTOr(@SuppressWarnings("unused") TOr node)
    {
        this.index = 23;
    }

    @Override
    public void caseTXor(@SuppressWarnings("unused") TXor node)
    {
        this.index = 24;
    }

    @Override
    public void caseTImplies(@SuppressWarnings("unused") TImplies node)
    {
        this.index = 25;
    }

    @Override
    public void caseTLPar(@SuppressWarnings("unused") TLPar node)
    {
        this.index = 26;
    }

    @Override
    public void caseTRPar(@SuppressWarnings("unused") TRPar node)
    {
        this.index = 27;
    }

    @Override
    public void caseTLBracket(@SuppressWarnings("unused") TLBracket node)
    {
        this.index = 28;
    }

    @Override
    public void caseTRBracket(@SuppressWarnings("unused") TRBracket node)
    {
        this.index = 29;
    }

    @Override
    public void caseTLBrace(@SuppressWarnings("unused") TLBrace node)
    {
        this.index = 30;
    }

    @Override
    public void caseTRBrace(@SuppressWarnings("unused") TRBrace node)
    {
        this.index = 31;
    }

    @Override
    public void caseTSemicolon(@SuppressWarnings("unused") TSemicolon node)
    {
        this.index = 32;
    }

    @Override
    public void caseTDcolon(@SuppressWarnings("unused") TDcolon node)
    {
        this.index = 33;
    }

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 34;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 35;
    }

    @Override
    public void caseTAt(@SuppressWarnings("unused") TAt node)
    {
        this.index = 36;
    }

    @Override
    public void caseTBar(@SuppressWarnings("unused") TBar node)
    {
        this.index = 37;
    }

    @Override
    public void caseTDdot(@SuppressWarnings("unused") TDdot node)
    {
        this.index = 38;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 39;
    }

    @Override
    public void caseTThen(@SuppressWarnings("unused") TThen node)
    {
        this.index = 40;
    }

    @Override
    public void caseTElse(@SuppressWarnings("unused") TElse node)
    {
        this.index = 41;
    }

    @Override
    public void caseTEndif(@SuppressWarnings("unused") TEndif node)
    {
        this.index = 42;
    }

    @Override
    public void caseTBooleanLiteral(@SuppressWarnings("unused") TBooleanLiteral node)
    {
        this.index = 43;
    }

    @Override
    public void caseTLet(@SuppressWarnings("unused") TLet node)
    {
        this.index = 44;
    }

    @Override
    public void caseTIn(@SuppressWarnings("unused") TIn node)
    {
        this.index = 45;
    }

    @Override
    public void caseTPackage(@SuppressWarnings("unused") TPackage node)
    {
        this.index = 46;
    }

    @Override
    public void caseTEndpackage(@SuppressWarnings("unused") TEndpackage node)
    {
        this.index = 47;
    }

    @Override
    public void caseTNumberLiteral(@SuppressWarnings("unused") TNumberLiteral node)
    {
        this.index = 48;
    }

    @Override
    public void caseTStringLiteral(@SuppressWarnings("unused") TStringLiteral node)
    {
        this.index = 49;
    }

    @Override
    public void caseTIdentifier(@SuppressWarnings("unused") TIdentifier node)
    {
        this.index = 50;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 51;
    }
}
