/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import java.util.*;
import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class AActualParameterList extends PActualParameterList
{
    private PExpression _expression_;
    private final LinkedList<PNextExpr> _nextExpr_ = new LinkedList<PNextExpr>();

    public AActualParameterList()
    {
        // Constructor
    }

    public AActualParameterList(
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") List<?> _nextExpr_)
    {
        // Constructor
        setExpression(_expression_);

        setNextExpr(_nextExpr_);

    }

    @Override
    public Object clone()
    {
        return new AActualParameterList(
            cloneNode(this._expression_),
            cloneList(this._nextExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAActualParameterList(this);
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public LinkedList<PNextExpr> getNextExpr()
    {
        return this._nextExpr_;
    }

    public void setNextExpr(List<?> list)
    {
        for(PNextExpr e : this._nextExpr_)
        {
            e.parent(null);
        }
        this._nextExpr_.clear();

        for(Object obj_e : list)
        {
            PNextExpr e = (PNextExpr) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._nextExpr_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression_)
            + toString(this._nextExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._nextExpr_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator<PNextExpr> i = this._nextExpr_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PNextExpr) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
