/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class AAddContextOperationName extends PContextOperationName
{
    private PAddOperator _addOperator_;

    public AAddContextOperationName()
    {
        // Constructor
    }

    public AAddContextOperationName(
        @SuppressWarnings("hiding") PAddOperator _addOperator_)
    {
        // Constructor
        setAddOperator(_addOperator_);

    }

    @Override
    public Object clone()
    {
        return new AAddContextOperationName(
            cloneNode(this._addOperator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAddContextOperationName(this);
    }

    public PAddOperator getAddOperator()
    {
        return this._addOperator_;
    }

    public void setAddOperator(PAddOperator node)
    {
        if(this._addOperator_ != null)
        {
            this._addOperator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._addOperator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._addOperator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._addOperator_ == child)
        {
            this._addOperator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._addOperator_ == oldChild)
        {
            setAddOperator((PAddOperator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
