/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class ABagCollectionKind extends PCollectionKind
{
    private TBag _bag_;

    public ABagCollectionKind()
    {
        // Constructor
    }

    public ABagCollectionKind(
        @SuppressWarnings("hiding") TBag _bag_)
    {
        // Constructor
        setBag(_bag_);

    }

    @Override
    public Object clone()
    {
        return new ABagCollectionKind(
            cloneNode(this._bag_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABagCollectionKind(this);
    }

    public TBag getBag()
    {
        return this._bag_;
    }

    public void setBag(TBag node)
    {
        if(this._bag_ != null)
        {
            this._bag_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bag_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bag_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bag_ == child)
        {
            this._bag_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bag_ == oldChild)
        {
            setBag((TBag) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
