/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class ABooleanOperation extends PBooleanOperation
{
    private PBooleanOperator _booleanOperator_;
    private PRelationalExpression _relationalExpression_;

    public ABooleanOperation()
    {
        // Constructor
    }

    public ABooleanOperation(
        @SuppressWarnings("hiding") PBooleanOperator _booleanOperator_,
        @SuppressWarnings("hiding") PRelationalExpression _relationalExpression_)
    {
        // Constructor
        setBooleanOperator(_booleanOperator_);

        setRelationalExpression(_relationalExpression_);

    }

    @Override
    public Object clone()
    {
        return new ABooleanOperation(
            cloneNode(this._booleanOperator_),
            cloneNode(this._relationalExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABooleanOperation(this);
    }

    public PBooleanOperator getBooleanOperator()
    {
        return this._booleanOperator_;
    }

    public void setBooleanOperator(PBooleanOperator node)
    {
        if(this._booleanOperator_ != null)
        {
            this._booleanOperator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._booleanOperator_ = node;
    }

    public PRelationalExpression getRelationalExpression()
    {
        return this._relationalExpression_;
    }

    public void setRelationalExpression(PRelationalExpression node)
    {
        if(this._relationalExpression_ != null)
        {
            this._relationalExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relationalExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._booleanOperator_)
            + toString(this._relationalExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._booleanOperator_ == child)
        {
            this._booleanOperator_ = null;
            return;
        }

        if(this._relationalExpression_ == child)
        {
            this._relationalExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._booleanOperator_ == oldChild)
        {
            setBooleanOperator((PBooleanOperator) newChild);
            return;
        }

        if(this._relationalExpression_ == oldChild)
        {
            setRelationalExpression((PRelationalExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
