/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class ACollectionTypeSpecifier extends PTypeSpecifier
{
    private PCollectionType _collectionType_;

    public ACollectionTypeSpecifier()
    {
        // Constructor
    }

    public ACollectionTypeSpecifier(
        @SuppressWarnings("hiding") PCollectionType _collectionType_)
    {
        // Constructor
        setCollectionType(_collectionType_);

    }

    @Override
    public Object clone()
    {
        return new ACollectionTypeSpecifier(
            cloneNode(this._collectionType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACollectionTypeSpecifier(this);
    }

    public PCollectionType getCollectionType()
    {
        return this._collectionType_;
    }

    public void setCollectionType(PCollectionType node)
    {
        if(this._collectionType_ != null)
        {
            this._collectionType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._collectionType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._collectionType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._collectionType_ == child)
        {
            this._collectionType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._collectionType_ == oldChild)
        {
            setCollectionType((PCollectionType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
