/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class ACollectionType extends PCollectionType
{
    private PCollectionKind _collectionKind_;
    private TLPar _lPar_;
    private PSimpleTypeSpecifier _simpleTypeSpecifier_;
    private TRPar _rPar_;

    public ACollectionType()
    {
        // Constructor
    }

    public ACollectionType(
        @SuppressWarnings("hiding") PCollectionKind _collectionKind_,
        @SuppressWarnings("hiding") TLPar _lPar_,
        @SuppressWarnings("hiding") PSimpleTypeSpecifier _simpleTypeSpecifier_,
        @SuppressWarnings("hiding") TRPar _rPar_)
    {
        // Constructor
        setCollectionKind(_collectionKind_);

        setLPar(_lPar_);

        setSimpleTypeSpecifier(_simpleTypeSpecifier_);

        setRPar(_rPar_);

    }

    @Override
    public Object clone()
    {
        return new ACollectionType(
            cloneNode(this._collectionKind_),
            cloneNode(this._lPar_),
            cloneNode(this._simpleTypeSpecifier_),
            cloneNode(this._rPar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACollectionType(this);
    }

    public PCollectionKind getCollectionKind()
    {
        return this._collectionKind_;
    }

    public void setCollectionKind(PCollectionKind node)
    {
        if(this._collectionKind_ != null)
        {
            this._collectionKind_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._collectionKind_ = node;
    }

    public TLPar getLPar()
    {
        return this._lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(this._lPar_ != null)
        {
            this._lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lPar_ = node;
    }

    public PSimpleTypeSpecifier getSimpleTypeSpecifier()
    {
        return this._simpleTypeSpecifier_;
    }

    public void setSimpleTypeSpecifier(PSimpleTypeSpecifier node)
    {
        if(this._simpleTypeSpecifier_ != null)
        {
            this._simpleTypeSpecifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simpleTypeSpecifier_ = node;
    }

    public TRPar getRPar()
    {
        return this._rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(this._rPar_ != null)
        {
            this._rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rPar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._collectionKind_)
            + toString(this._lPar_)
            + toString(this._simpleTypeSpecifier_)
            + toString(this._rPar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._collectionKind_ == child)
        {
            this._collectionKind_ = null;
            return;
        }

        if(this._lPar_ == child)
        {
            this._lPar_ = null;
            return;
        }

        if(this._simpleTypeSpecifier_ == child)
        {
            this._simpleTypeSpecifier_ = null;
            return;
        }

        if(this._rPar_ == child)
        {
            this._rPar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._collectionKind_ == oldChild)
        {
            setCollectionKind((PCollectionKind) newChild);
            return;
        }

        if(this._lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(this._simpleTypeSpecifier_ == oldChild)
        {
            setSimpleTypeSpecifier((PSimpleTypeSpecifier) newChild);
            return;
        }

        if(this._rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
