/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class ACollectionPropertyInvocation extends PPropertyInvocation
{
    private TArrow _arrow_;
    private PPropertyCall _propertyCall_;

    public ACollectionPropertyInvocation()
    {
        // Constructor
    }

    public ACollectionPropertyInvocation(
        @SuppressWarnings("hiding") TArrow _arrow_,
        @SuppressWarnings("hiding") PPropertyCall _propertyCall_)
    {
        // Constructor
        setArrow(_arrow_);

        setPropertyCall(_propertyCall_);

    }

    @Override
    public Object clone()
    {
        return new ACollectionPropertyInvocation(
            cloneNode(this._arrow_),
            cloneNode(this._propertyCall_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACollectionPropertyInvocation(this);
    }

    public TArrow getArrow()
    {
        return this._arrow_;
    }

    public void setArrow(TArrow node)
    {
        if(this._arrow_ != null)
        {
            this._arrow_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrow_ = node;
    }

    public PPropertyCall getPropertyCall()
    {
        return this._propertyCall_;
    }

    public void setPropertyCall(PPropertyCall node)
    {
        if(this._propertyCall_ != null)
        {
            this._propertyCall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._propertyCall_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arrow_)
            + toString(this._propertyCall_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arrow_ == child)
        {
            this._arrow_ = null;
            return;
        }

        if(this._propertyCall_ == child)
        {
            this._propertyCall_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arrow_ == oldChild)
        {
            setArrow((TArrow) newChild);
            return;
        }

        if(this._propertyCall_ == oldChild)
        {
            setPropertyCall((PPropertyCall) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
