/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class ADivMultiplyOperator extends PMultiplyOperator
{
    private TDiv _div_;

    public ADivMultiplyOperator()
    {
        // Constructor
    }

    public ADivMultiplyOperator(
        @SuppressWarnings("hiding") TDiv _div_)
    {
        // Constructor
        setDiv(_div_);

    }

    @Override
    public Object clone()
    {
        return new ADivMultiplyOperator(
            cloneNode(this._div_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivMultiplyOperator(this);
    }

    public TDiv getDiv()
    {
        return this._div_;
    }

    public void setDiv(TDiv node)
    {
        if(this._div_ != null)
        {
            this._div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._div_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._div_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._div_ == child)
        {
            this._div_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
