/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class AFormalParameterList extends PFormalParameterList
{
    private PParamList _paramList_;

    public AFormalParameterList()
    {
        // Constructor
    }

    public AFormalParameterList(
        @SuppressWarnings("hiding") PParamList _paramList_)
    {
        // Constructor
        setParamList(_paramList_);

    }

    @Override
    public Object clone()
    {
        return new AFormalParameterList(
            cloneNode(this._paramList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFormalParameterList(this);
    }

    public PParamList getParamList()
    {
        return this._paramList_;
    }

    public void setParamList(PParamList node)
    {
        if(this._paramList_ != null)
        {
            this._paramList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paramList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._paramList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._paramList_ == child)
        {
            this._paramList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._paramList_ == oldChild)
        {
            setParamList((PParamList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
