/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class AImplicativeLogicalOperator extends PLogicalOperator
{
    private PImpliesOperator _impliesOperator_;

    public AImplicativeLogicalOperator()
    {
        // Constructor
    }

    public AImplicativeLogicalOperator(
        @SuppressWarnings("hiding") PImpliesOperator _impliesOperator_)
    {
        // Constructor
        setImpliesOperator(_impliesOperator_);

    }

    @Override
    public Object clone()
    {
        return new AImplicativeLogicalOperator(
            cloneNode(this._impliesOperator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAImplicativeLogicalOperator(this);
    }

    public PImpliesOperator getImpliesOperator()
    {
        return this._impliesOperator_;
    }

    public void setImpliesOperator(PImpliesOperator node)
    {
        if(this._impliesOperator_ != null)
        {
            this._impliesOperator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._impliesOperator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._impliesOperator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._impliesOperator_ == child)
        {
            this._impliesOperator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._impliesOperator_ == oldChild)
        {
            setImpliesOperator((PImpliesOperator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
