/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class AImpliesOperator extends PImpliesOperator
{
    private TImplies _implies_;

    public AImpliesOperator()
    {
        // Constructor
    }

    public AImpliesOperator(
        @SuppressWarnings("hiding") TImplies _implies_)
    {
        // Constructor
        setImplies(_implies_);

    }

    @Override
    public Object clone()
    {
        return new AImpliesOperator(
            cloneNode(this._implies_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAImpliesOperator(this);
    }

    public TImplies getImplies()
    {
        return this._implies_;
    }

    public void setImplies(TImplies node)
    {
        if(this._implies_ != null)
        {
            this._implies_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._implies_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._implies_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._implies_ == child)
        {
            this._implies_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._implies_ == oldChild)
        {
            setImplies((TImplies) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
