/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class AImplication extends PImplication
{
    private PImpliesOperator _impliesOperator_;
    private PBooleanExpression _booleanExpression_;

    public AImplication()
    {
        // Constructor
    }

    public AImplication(
        @SuppressWarnings("hiding") PImpliesOperator _impliesOperator_,
        @SuppressWarnings("hiding") PBooleanExpression _booleanExpression_)
    {
        // Constructor
        setImpliesOperator(_impliesOperator_);

        setBooleanExpression(_booleanExpression_);

    }

    @Override
    public Object clone()
    {
        return new AImplication(
            cloneNode(this._impliesOperator_),
            cloneNode(this._booleanExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAImplication(this);
    }

    public PImpliesOperator getImpliesOperator()
    {
        return this._impliesOperator_;
    }

    public void setImpliesOperator(PImpliesOperator node)
    {
        if(this._impliesOperator_ != null)
        {
            this._impliesOperator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._impliesOperator_ = node;
    }

    public PBooleanExpression getBooleanExpression()
    {
        return this._booleanExpression_;
    }

    public void setBooleanExpression(PBooleanExpression node)
    {
        if(this._booleanExpression_ != null)
        {
            this._booleanExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._booleanExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._impliesOperator_)
            + toString(this._booleanExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._impliesOperator_ == child)
        {
            this._impliesOperator_ = null;
            return;
        }

        if(this._booleanExpression_ == child)
        {
            this._booleanExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._impliesOperator_ == oldChild)
        {
            setImpliesOperator((PImpliesOperator) newChild);
            return;
        }

        if(this._booleanExpression_ == oldChild)
        {
            setBooleanExpression((PBooleanExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
