/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import java.util.*;
import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class ANameList extends PNameList
{
    private PName _name_;
    private final LinkedList<PNextName> _nextName_ = new LinkedList<PNextName>();

    public ANameList()
    {
        // Constructor
    }

    public ANameList(
        @SuppressWarnings("hiding") PName _name_,
        @SuppressWarnings("hiding") List<?> _nextName_)
    {
        // Constructor
        setName(_name_);

        setNextName(_nextName_);

    }

    @Override
    public Object clone()
    {
        return new ANameList(
            cloneNode(this._name_),
            cloneList(this._nextName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANameList(this);
    }

    public PName getName()
    {
        return this._name_;
    }

    public void setName(PName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public LinkedList<PNextName> getNextName()
    {
        return this._nextName_;
    }

    public void setNextName(List<?> list)
    {
        for(PNextName e : this._nextName_)
        {
            e.parent(null);
        }
        this._nextName_.clear();

        for(Object obj_e : list)
        {
            PNextName e = (PNextName) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._nextName_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._nextName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._nextName_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((PName) newChild);
            return;
        }

        for(ListIterator<PNextName> i = this._nextName_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PNextName) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
