/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class ANameQualifier extends PNameQualifier
{
    private PName _name_;
    private TDcolon _dcolon_;

    public ANameQualifier()
    {
        // Constructor
    }

    public ANameQualifier(
        @SuppressWarnings("hiding") PName _name_,
        @SuppressWarnings("hiding") TDcolon _dcolon_)
    {
        // Constructor
        setName(_name_);

        setDcolon(_dcolon_);

    }

    @Override
    public Object clone()
    {
        return new ANameQualifier(
            cloneNode(this._name_),
            cloneNode(this._dcolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANameQualifier(this);
    }

    public PName getName()
    {
        return this._name_;
    }

    public void setName(PName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public TDcolon getDcolon()
    {
        return this._dcolon_;
    }

    public void setDcolon(TDcolon node)
    {
        if(this._dcolon_ != null)
        {
            this._dcolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dcolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._dcolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._dcolon_ == child)
        {
            this._dcolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((PName) newChild);
            return;
        }

        if(this._dcolon_ == oldChild)
        {
            setDcolon((TDcolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
