/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class ANextCollectionItem extends PNextCollectionItem
{
    private TComma _comma_;
    private PCollectionItem _collectionItem_;

    public ANextCollectionItem()
    {
        // Constructor
    }

    public ANextCollectionItem(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PCollectionItem _collectionItem_)
    {
        // Constructor
        setComma(_comma_);

        setCollectionItem(_collectionItem_);

    }

    @Override
    public Object clone()
    {
        return new ANextCollectionItem(
            cloneNode(this._comma_),
            cloneNode(this._collectionItem_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANextCollectionItem(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PCollectionItem getCollectionItem()
    {
        return this._collectionItem_;
    }

    public void setCollectionItem(PCollectionItem node)
    {
        if(this._collectionItem_ != null)
        {
            this._collectionItem_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._collectionItem_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._collectionItem_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._collectionItem_ == child)
        {
            this._collectionItem_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._collectionItem_ == oldChild)
        {
            setCollectionItem((PCollectionItem) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
