/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class ANextParam extends PNextParam
{
    private TComma _comma_;
    private PFormalParameter _formalParameter_;

    public ANextParam()
    {
        // Constructor
    }

    public ANextParam(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PFormalParameter _formalParameter_)
    {
        // Constructor
        setComma(_comma_);

        setFormalParameter(_formalParameter_);

    }

    @Override
    public Object clone()
    {
        return new ANextParam(
            cloneNode(this._comma_),
            cloneNode(this._formalParameter_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANextParam(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PFormalParameter getFormalParameter()
    {
        return this._formalParameter_;
    }

    public void setFormalParameter(PFormalParameter node)
    {
        if(this._formalParameter_ != null)
        {
            this._formalParameter_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._formalParameter_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._formalParameter_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._formalParameter_ == child)
        {
            this._formalParameter_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._formalParameter_ == oldChild)
        {
            setFormalParameter((PFormalParameter) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
