/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class AObjectPropertyInvocation extends PPropertyInvocation
{
    private TDot _dot_;
    private PPropertyCall _propertyCall_;

    public AObjectPropertyInvocation()
    {
        // Constructor
    }

    public AObjectPropertyInvocation(
        @SuppressWarnings("hiding") TDot _dot_,
        @SuppressWarnings("hiding") PPropertyCall _propertyCall_)
    {
        // Constructor
        setDot(_dot_);

        setPropertyCall(_propertyCall_);

    }

    @Override
    public Object clone()
    {
        return new AObjectPropertyInvocation(
            cloneNode(this._dot_),
            cloneNode(this._propertyCall_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAObjectPropertyInvocation(this);
    }

    public TDot getDot()
    {
        return this._dot_;
    }

    public void setDot(TDot node)
    {
        if(this._dot_ != null)
        {
            this._dot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dot_ = node;
    }

    public PPropertyCall getPropertyCall()
    {
        return this._propertyCall_;
    }

    public void setPropertyCall(PPropertyCall node)
    {
        if(this._propertyCall_ != null)
        {
            this._propertyCall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._propertyCall_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dot_)
            + toString(this._propertyCall_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dot_ == child)
        {
            this._dot_ = null;
            return;
        }

        if(this._propertyCall_ == child)
        {
            this._propertyCall_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dot_ == oldChild)
        {
            setDot((TDot) newChild);
            return;
        }

        if(this._propertyCall_ == oldChild)
        {
            setPropertyCall((PPropertyCall) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
