/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import java.util.*;
import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class AOclFile extends POclFile
{
    private final LinkedList<PConstraint> _constraint_ = new LinkedList<PConstraint>();

    public AOclFile()
    {
        // Constructor
    }

    public AOclFile(
        @SuppressWarnings("hiding") List<?> _constraint_)
    {
        // Constructor
        setConstraint(_constraint_);

    }

    @Override
    public Object clone()
    {
        return new AOclFile(
            cloneList(this._constraint_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOclFile(this);
    }

    public LinkedList<PConstraint> getConstraint()
    {
        return this._constraint_;
    }

    public void setConstraint(List<?> list)
    {
        for(PConstraint e : this._constraint_)
        {
            e.parent(null);
        }
        this._constraint_.clear();

        for(Object obj_e : list)
        {
            PConstraint e = (PConstraint) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._constraint_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._constraint_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._constraint_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PConstraint> i = this._constraint_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PConstraint) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
