/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class AOclExpression extends POclExpression
{
    private PLetDeclaration _letDeclaration_;
    private PExpression _expression_;

    public AOclExpression()
    {
        // Constructor
    }

    public AOclExpression(
        @SuppressWarnings("hiding") PLetDeclaration _letDeclaration_,
        @SuppressWarnings("hiding") PExpression _expression_)
    {
        // Constructor
        setLetDeclaration(_letDeclaration_);

        setExpression(_expression_);

    }

    @Override
    public Object clone()
    {
        return new AOclExpression(
            cloneNode(this._letDeclaration_),
            cloneNode(this._expression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOclExpression(this);
    }

    public PLetDeclaration getLetDeclaration()
    {
        return this._letDeclaration_;
    }

    public void setLetDeclaration(PLetDeclaration node)
    {
        if(this._letDeclaration_ != null)
        {
            this._letDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._letDeclaration_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._letDeclaration_)
            + toString(this._expression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._letDeclaration_ == child)
        {
            this._letDeclaration_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._letDeclaration_ == oldChild)
        {
            setLetDeclaration((PLetDeclaration) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
