/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class AOclAnyTypeSpecifier extends PTypeSpecifier
{
    private PSimpleTypeSpecifier _simpleTypeSpecifier_;

    public AOclAnyTypeSpecifier()
    {
        // Constructor
    }

    public AOclAnyTypeSpecifier(
        @SuppressWarnings("hiding") PSimpleTypeSpecifier _simpleTypeSpecifier_)
    {
        // Constructor
        setSimpleTypeSpecifier(_simpleTypeSpecifier_);

    }

    @Override
    public Object clone()
    {
        return new AOclAnyTypeSpecifier(
            cloneNode(this._simpleTypeSpecifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOclAnyTypeSpecifier(this);
    }

    public PSimpleTypeSpecifier getSimpleTypeSpecifier()
    {
        return this._simpleTypeSpecifier_;
    }

    public void setSimpleTypeSpecifier(PSimpleTypeSpecifier node)
    {
        if(this._simpleTypeSpecifier_ != null)
        {
            this._simpleTypeSpecifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simpleTypeSpecifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._simpleTypeSpecifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._simpleTypeSpecifier_ == child)
        {
            this._simpleTypeSpecifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._simpleTypeSpecifier_ == oldChild)
        {
            setSimpleTypeSpecifier((PSimpleTypeSpecifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
