/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import java.util.*;
import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class AOclFile extends POclFile
{
    private final LinkedList<POclPackage> _oclPackage_ = new LinkedList<POclPackage>();

    public AOclFile()
    {
        // Constructor
    }

    public AOclFile(
        @SuppressWarnings("hiding") List<?> _oclPackage_)
    {
        // Constructor
        setOclPackage(_oclPackage_);

    }

    @Override
    public Object clone()
    {
        return new AOclFile(
            cloneList(this._oclPackage_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOclFile(this);
    }

    public LinkedList<POclPackage> getOclPackage()
    {
        return this._oclPackage_;
    }

    public void setOclPackage(List<?> list)
    {
        for(POclPackage e : this._oclPackage_)
        {
            e.parent(null);
        }
        this._oclPackage_.clear();

        for(Object obj_e : list)
        {
            POclPackage e = (POclPackage) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._oclPackage_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._oclPackage_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._oclPackage_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<POclPackage> i = this._oclPackage_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((POclPackage) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
