/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import java.util.*;
import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class APathName extends PPathName
{
    private final LinkedList<PNameQualifier> _nameQualifier_ = new LinkedList<PNameQualifier>();
    private PName _name_;

    public APathName()
    {
        // Constructor
    }

    public APathName(
        @SuppressWarnings("hiding") List<?> _nameQualifier_,
        @SuppressWarnings("hiding") PName _name_)
    {
        // Constructor
        setNameQualifier(_nameQualifier_);

        setName(_name_);

    }

    @Override
    public Object clone()
    {
        return new APathName(
            cloneList(this._nameQualifier_),
            cloneNode(this._name_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPathName(this);
    }

    public LinkedList<PNameQualifier> getNameQualifier()
    {
        return this._nameQualifier_;
    }

    public void setNameQualifier(List<?> list)
    {
        for(PNameQualifier e : this._nameQualifier_)
        {
            e.parent(null);
        }
        this._nameQualifier_.clear();

        for(Object obj_e : list)
        {
            PNameQualifier e = (PNameQualifier) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._nameQualifier_.add(e);
        }
    }

    public PName getName()
    {
        return this._name_;
    }

    public void setName(PName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nameQualifier_)
            + toString(this._name_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nameQualifier_.remove(child))
        {
            return;
        }

        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PNameQualifier> i = this._nameQualifier_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PNameQualifier) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._name_ == oldChild)
        {
            setName((PName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
