/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import java.util.*;
import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class APostfixExpression extends PPostfixExpression
{
    private PPrimaryExpression _primaryExpression_;
    private final LinkedList<PPropertyInvocation> _propertyInvocation_ = new LinkedList<PPropertyInvocation>();

    public APostfixExpression()
    {
        // Constructor
    }

    public APostfixExpression(
        @SuppressWarnings("hiding") PPrimaryExpression _primaryExpression_,
        @SuppressWarnings("hiding") List<?> _propertyInvocation_)
    {
        // Constructor
        setPrimaryExpression(_primaryExpression_);

        setPropertyInvocation(_propertyInvocation_);

    }

    @Override
    public Object clone()
    {
        return new APostfixExpression(
            cloneNode(this._primaryExpression_),
            cloneList(this._propertyInvocation_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPostfixExpression(this);
    }

    public PPrimaryExpression getPrimaryExpression()
    {
        return this._primaryExpression_;
    }

    public void setPrimaryExpression(PPrimaryExpression node)
    {
        if(this._primaryExpression_ != null)
        {
            this._primaryExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._primaryExpression_ = node;
    }

    public LinkedList<PPropertyInvocation> getPropertyInvocation()
    {
        return this._propertyInvocation_;
    }

    public void setPropertyInvocation(List<?> list)
    {
        for(PPropertyInvocation e : this._propertyInvocation_)
        {
            e.parent(null);
        }
        this._propertyInvocation_.clear();

        for(Object obj_e : list)
        {
            PPropertyInvocation e = (PPropertyInvocation) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._propertyInvocation_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._primaryExpression_)
            + toString(this._propertyInvocation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._primaryExpression_ == child)
        {
            this._primaryExpression_ = null;
            return;
        }

        if(this._propertyInvocation_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._primaryExpression_ == oldChild)
        {
            setPrimaryExpression((PPrimaryExpression) newChild);
            return;
        }

        for(ListIterator<PPropertyInvocation> i = this._propertyInvocation_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PPropertyInvocation) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
