/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class APostConditionStereotype extends PStereotype
{
    private TPost _post_;

    public APostConditionStereotype()
    {
        // Constructor
    }

    public APostConditionStereotype(
        @SuppressWarnings("hiding") TPost _post_)
    {
        // Constructor
        setPost(_post_);

    }

    @Override
    public Object clone()
    {
        return new APostConditionStereotype(
            cloneNode(this._post_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPostConditionStereotype(this);
    }

    public TPost getPost()
    {
        return this._post_;
    }

    public void setPost(TPost node)
    {
        if(this._post_ != null)
        {
            this._post_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._post_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._post_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._post_ == child)
        {
            this._post_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._post_ == oldChild)
        {
            setPost((TPost) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
