/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class APreConditionStereotype extends PStereotype
{
    private TPre _pre_;

    public APreConditionStereotype()
    {
        // Constructor
    }

    public APreConditionStereotype(
        @SuppressWarnings("hiding") TPre _pre_)
    {
        // Constructor
        setPre(_pre_);

    }

    @Override
    public Object clone()
    {
        return new APreConditionStereotype(
            cloneNode(this._pre_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPreConditionStereotype(this);
    }

    public TPre getPre()
    {
        return this._pre_;
    }

    public void setPre(TPre node)
    {
        if(this._pre_ != null)
        {
            this._pre_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pre_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pre_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pre_ == child)
        {
            this._pre_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pre_ == oldChild)
        {
            setPre((TPre) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
