/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class APropertyCallPrimaryExpression extends PPrimaryExpression
{
    private PPropertyCall _propertyCall_;

    public APropertyCallPrimaryExpression()
    {
        // Constructor
    }

    public APropertyCallPrimaryExpression(
        @SuppressWarnings("hiding") PPropertyCall _propertyCall_)
    {
        // Constructor
        setPropertyCall(_propertyCall_);

    }

    @Override
    public Object clone()
    {
        return new APropertyCallPrimaryExpression(
            cloneNode(this._propertyCall_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPropertyCallPrimaryExpression(this);
    }

    public PPropertyCall getPropertyCall()
    {
        return this._propertyCall_;
    }

    public void setPropertyCall(PPropertyCall node)
    {
        if(this._propertyCall_ != null)
        {
            this._propertyCall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._propertyCall_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._propertyCall_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._propertyCall_ == child)
        {
            this._propertyCall_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._propertyCall_ == oldChild)
        {
            setPropertyCall((PPropertyCall) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
