/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class ARange extends PRange
{
    private TDdot _ddot_;
    private PExpression _expression_;

    public ARange()
    {
        // Constructor
    }

    public ARange(
        @SuppressWarnings("hiding") TDdot _ddot_,
        @SuppressWarnings("hiding") PExpression _expression_)
    {
        // Constructor
        setDdot(_ddot_);

        setExpression(_expression_);

    }

    @Override
    public Object clone()
    {
        return new ARange(
            cloneNode(this._ddot_),
            cloneNode(this._expression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARange(this);
    }

    public TDdot getDdot()
    {
        return this._ddot_;
    }

    public void setDdot(TDdot node)
    {
        if(this._ddot_ != null)
        {
            this._ddot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ddot_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ddot_)
            + toString(this._expression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ddot_ == child)
        {
            this._ddot_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ddot_ == oldChild)
        {
            setDdot((TDdot) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
