/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class ARelationalContextOperationName extends PContextOperationName
{
    private PRelationalOperator _relationalOperator_;

    public ARelationalContextOperationName()
    {
        // Constructor
    }

    public ARelationalContextOperationName(
        @SuppressWarnings("hiding") PRelationalOperator _relationalOperator_)
    {
        // Constructor
        setRelationalOperator(_relationalOperator_);

    }

    @Override
    public Object clone()
    {
        return new ARelationalContextOperationName(
            cloneNode(this._relationalOperator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelationalContextOperationName(this);
    }

    public PRelationalOperator getRelationalOperator()
    {
        return this._relationalOperator_;
    }

    public void setRelationalOperator(PRelationalOperator node)
    {
        if(this._relationalOperator_ != null)
        {
            this._relationalOperator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relationalOperator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relationalOperator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relationalOperator_ == child)
        {
            this._relationalOperator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._relationalOperator_ == oldChild)
        {
            setRelationalOperator((PRelationalOperator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
