/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class ASequenceCollectionKind extends PCollectionKind
{
    private TSequence _sequence_;

    public ASequenceCollectionKind()
    {
        // Constructor
    }

    public ASequenceCollectionKind(
        @SuppressWarnings("hiding") TSequence _sequence_)
    {
        // Constructor
        setSequence(_sequence_);

    }

    @Override
    public Object clone()
    {
        return new ASequenceCollectionKind(
            cloneNode(this._sequence_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequenceCollectionKind(this);
    }

    public TSequence getSequence()
    {
        return this._sequence_;
    }

    public void setSequence(TSequence node)
    {
        if(this._sequence_ != null)
        {
            this._sequence_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sequence_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sequence_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sequence_ == child)
        {
            this._sequence_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sequence_ == oldChild)
        {
            setSequence((TSequence) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
