/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class ATimeExpression extends PTimeExpression
{
    private TAt _at_;
    private TPre _pre_;

    public ATimeExpression()
    {
        // Constructor
    }

    public ATimeExpression(
        @SuppressWarnings("hiding") TAt _at_,
        @SuppressWarnings("hiding") TPre _pre_)
    {
        // Constructor
        setAt(_at_);

        setPre(_pre_);

    }

    @Override
    public Object clone()
    {
        return new ATimeExpression(
            cloneNode(this._at_),
            cloneNode(this._pre_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATimeExpression(this);
    }

    public TAt getAt()
    {
        return this._at_;
    }

    public void setAt(TAt node)
    {
        if(this._at_ != null)
        {
            this._at_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._at_ = node;
    }

    public TPre getPre()
    {
        return this._pre_;
    }

    public void setPre(TPre node)
    {
        if(this._pre_ != null)
        {
            this._pre_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pre_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._at_)
            + toString(this._pre_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._at_ == child)
        {
            this._at_ = null;
            return;
        }

        if(this._pre_ == child)
        {
            this._pre_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._at_ == oldChild)
        {
            setAt((TAt) newChild);
            return;
        }

        if(this._pre_ == oldChild)
        {
            setPre((TPre) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
