/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class TDcolon extends Token
{
    public TDcolon()
    {
        super.setText("::");
    }

    public TDcolon(int line, int pos)
    {
        super.setText("::");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDcolon(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDcolon(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDcolon text.");
    }
}
