/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class TEndpackage extends Token
{
    public TEndpackage()
    {
        super.setText("endpackage");
    }

    public TEndpackage(int line, int pos)
    {
        super.setText("endpackage");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEndpackage(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEndpackage(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEndpackage text.");
    }
}
