/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class TInv extends Token
{
    public TInv()
    {
        super.setText("inv");
    }

    public TInv(int line, int pos)
    {
        super.setText("inv");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInv(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInv(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInv text.");
    }
}
