/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class TPost extends Token
{
    public TPost()
    {
        super.setText("post");
    }

    public TPost(int line, int pos)
    {
        super.setText("post");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPost(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPost(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPost text.");
    }
}
