/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tuberlin.cs.cis.ocl.parser.node;

import de.tuberlin.cs.cis.ocl.parser.analysis.*;

@SuppressWarnings("nls")
public final class TSequence extends Token
{
    public TSequence()
    {
        super.setText("Sequence");
    }

    public TSequence(int line, int pos)
    {
        super.setText("Sequence");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSequence(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSequence(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSequence text.");
    }
}
