<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="example" nsURI="http://www.example.org/examples/example.ecore"
    nsPrefix="ex">
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="homePage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numPublications" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publication" ordered="false"
        upperBound="-1" eType="#//Publication" eOpposite="#//Publication/person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editedBook" ordered="false"
        upperBound="-1" eType="#//EditedBook" eOpposite="#//EditedBook/editor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authoredPublication" ordered="false"
        upperBound="-1" eType="#//AuthoredPublication" eOpposite="#//AuthoredPublication/author"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Publication">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" ordered="false"
        upperBound="-1" eType="#//Person" eOpposite="#//Person/publication"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Book" eSuperTypes="#//Publication">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numPages" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="homePage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publisher" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicationYear" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isbn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditedBook" eSuperTypes="#//Publication #//Book">
    <eStructuralFeatures xsi:type="ecore:EReference" name="editor" ordered="false"
        upperBound="-1" eType="#//Person" eOpposite="#//Person/editedBook"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bookSection" ordered="false"
        upperBound="-1" eType="#//BookSection" containment="true" eOpposite="#//BookSection/editedBook"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bookChapter" ordered="false"
        upperBound="-1" eType="#//BookChapter" containment="true" eOpposite="#//BookChapter/editedBook"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conferenceEdition" ordered="false"
        eType="#//ConferenceEdition" eOpposite="#//ConferenceEdition/editedBook"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuthoredBook" eSuperTypes="#//Book #//AuthoredPublication"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuthoredPublication" eSuperTypes="#//Publication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" ordered="false"
        upperBound="-1" eType="#//Person" eOpposite="#//Person/authoredPublication"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BookChapter" eSuperTypes="#//AuthoredPublication">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iniPage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endPage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conferencePaper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bookSection" ordered="false"
        eType="#//BookSection" eOpposite="#//BookSection/bookChapter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editedBook" ordered="false"
        eType="#//EditedBook" eOpposite="#//EditedBook/bookChapter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bookSeriesIssue" ordered="false"
        eType="#//BookSeriesIssue" eOpposite="#//BookSeriesIssue/bookChapter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JournalPaper" eSuperTypes="#//AuthoredPublication">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iniPage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endPage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conferencePaper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="journalSection" ordered="false"
        eType="#//JournalSection" eOpposite="#//JournalSection/journalPaper"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="journalIssue" ordered="false"
        lowerBound="1" eType="#//JournalIssue" eOpposite="#//JournalIssue/journalPaper"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BookSection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editedBook" ordered="false"
        eType="#//EditedBook" eOpposite="#//EditedBook/bookSection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bookChapter" ordered="false"
        upperBound="-1" eType="#//BookChapter" containment="true" eOpposite="#//BookChapter/bookSection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bookSeriesIssue" ordered="false"
        eType="#//BookSeriesIssue" eOpposite="#//BookSeriesIssue/bookSection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JournalSection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="journalPaper" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//JournalPaper" eOpposite="#//JournalPaper/journalSection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="journalIssue" lowerBound="1"
        eType="#//JournalIssue" eOpposite="#//JournalIssue/journalSection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JournalIssue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="month" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numPages" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="journalSection" ordered="false"
        upperBound="-1" eType="#//JournalSection" containment="true" eOpposite="#//JournalSection/journalIssue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="journalPaper" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//JournalPaper" containment="true"
        eOpposite="#//JournalPaper/journalIssue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="journalVolume" lowerBound="1"
        eType="#//JournalVolume" eOpposite="#//JournalVolume/journalIssue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conferenceEdition" eType="#//ConferenceEdition"
        eOpposite="#//ConferenceEdition/journalIssue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BookSeriesIssue" eSuperTypes="#//Book">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bookSection" ordered="false"
        upperBound="-1" eType="#//BookSection" containment="true" eOpposite="#//BookSection/bookSeriesIssue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bookChapter" ordered="false"
        upperBound="-1" eType="#//BookChapter" containment="true" eOpposite="#//BookChapter/bookSeriesIssue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bookSeries" lowerBound="1"
        eType="#//BookSeries" eOpposite="#//BookSeries/bookSeriesIssue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conferenceEdition" eType="#//ConferenceEdition"
        eOpposite="#//ConferenceEdition/bookSeriesIssue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BookSeries">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publisher" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bookSeriesIssue" ordered="false"
        upperBound="-1" eType="#//BookSeriesIssue" containment="true" eOpposite="#//BookSeriesIssue/bookSeries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConferenceEdition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="homePage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editedBook" eType="#//EditedBook"
        eOpposite="#//EditedBook/conferenceEdition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bookSeriesIssue" eType="#//BookSeriesIssue"
        eOpposite="#//BookSeriesIssue/conferenceEdition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="journalIssue" eType="#//JournalIssue"
        eOpposite="#//JournalIssue/conferenceEdition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conferenceSeries" lowerBound="1"
        eType="#//ConferenceSeries" eOpposite="#//ConferenceSeries/conferenceEdition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConferenceSeries">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acronym" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conferenceEdition" ordered="false"
        upperBound="-1" eType="#//ConferenceEdition" containment="true" eOpposite="#//ConferenceEdition/conferenceSeries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JournalVolume">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="journalIssue" ordered="false"
        upperBound="-1" eType="#//JournalIssue" containment="true" eOpposite="#//JournalIssue/journalVolume"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="journal" lowerBound="1"
        eType="#//Journal" eOpposite="#//Journal/journalVolume"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Journal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="issn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="journalVolume" ordered="false"
        upperBound="-1" eType="#//JournalVolume" containment="true" eOpposite="#//JournalVolume/journal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conferenceSeries" upperBound="-1"
        eType="#//ConferenceSeries" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="journal" upperBound="-1"
        eType="#//Journal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bookSeries" upperBound="-1"
        eType="#//BookSeries" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publication" ordered="false"
        upperBound="-1" eType="#//Publication" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" ordered="false"
        upperBound="-1" eType="#//Person" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
